packaging_format = 2

id = "whitebophir"
name = "Whitebophir"
description.en = "Open source vector collaborative board"
description.fr = "Tableau de dessin vectoriel collaboratif open source"

version = "1.19.0~ynh1"

maintainers = ["bwjtkw", "oiseauroch"]

[upstream]
license = "AGPL-3.0-only"
demo = "wbo.ophir.dev"
code = "https://github.com/lovasoa/whitebophir"
website = "https://wbo.ophir.dev/"
cpe = "???" # FIXME: optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is sort of a standard id for applications defined by the NIST. In particular, Yunohost may use this is in the future to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search. For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
fund = "???" # FIXME: optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.

[integration]
yunohost = ">= 11.0.9"
architectures = "all" # FIXME: can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386"]
multi_instance = true
ldap = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
sso = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "path"
    default = "/whitebophir"

    [install.init_main_permission]
    help.en = "This application will be accessible publiquely. Anyone will be able to create boards."
    help.fr = "Cette application sera accessible publiquement, n'importe qui pourra créer des tableaux"
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/lovasoa/whitebophir/archive/refs/tags/v1.19.0.tar.gz"
        sha256 = "eec748144b016565e55133824a23cd2478c79544ae08f9a7028e99d2e22adc8e"


    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
