#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "whitebophir"
name = "Whitebophir"
description.en = "Open source vector collaborative board"
description.fr = "Tableau de dessin vectoriel collaboratif open source"

version = "1.22.0~ynh1"

maintainers = ["bwjtkw", "oiseauroch"]

[upstream]
license = "AGPL-3.0-only"
demo = "wbo.ophir.dev"
code = "https://github.com/lovasoa/whitebophir"
website = "https://wbo.ophir.dev/"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "350M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/whitebophir"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/lovasoa/whitebophir/archive/refs/tags/v1.22.0.tar.gz"
    sha256 = "b4155157ab44bfb2e5f43c29f22a574c55046a7e1723d77728c226d1425760ba"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
