packaging_format = 2

id = "whitebophir"
name = "Whitebophir"
description.en = "Open source vector collaborative board"
description.fr = "Tableau de dessin vectoriel collaboratif open source"

version = "1.19.0~ynh1"

maintainers = ["bwjtkw", "oiseauroch"]

[upstream]
license = "AGPL-3.0-only"
demo = "wbo.ophir.dev"
code = "https://github.com/lovasoa/whitebophir"
website = "https://wbo.ophir.dev/"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/whitebophir"

    [install.init_main_permission]
    help.en = "This application will be accessible publiquely. Anyone will be able to create boards."
    help.fr = "Cette application sera accessible publiquement, n'importe qui pourra créer des tableaux"
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/lovasoa/whitebophir/archive/refs/tags/v1.19.0.tar.gz"
        sha256 = "eec748144b016565e55133824a23cd2478c79544ae08f9a7028e99d2e22adc8e"

    [resources.system_user]

    [resources.install_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"
