packaging_format = 2

id = "whitebophir"
name = "Whitebophir"
description.en = "Open source vector collaborative board"
description.fr = "Tableau de dessin vectoriel collaboratif open source"

version = "1.20.0~ynh1"

maintainers = ["bwjtkw", "oiseauroch"]

[upstream]
license = "AGPL-3.0-only"
demo = "wbo.ophir.dev"
code = "https://github.com/lovasoa/whitebophir"
website = "https://wbo.ophir.dev/"

[integration]
yunohost = ">= 11.2.18"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "350M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/whitebophir"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/lovasoa/whitebophir/archive/refs/tags/v1.20.0.tar.gz"
        sha256 = "41c5b3b9a83c83f6407171a7a569bd66d1f27529d3ffe0b94238cb0d8bd9c656"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"
