#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "whitebophir"
name = "Whitebophir"
description.en = "Vector drawing collaborative board"
description.fr = "Tableau de dessin vectoriel collaboratif"

version = "1.27.1~ynh1"

maintainers = ["bwjtkw", "oiseauroch"]

[upstream]
license = "AGPL-3.0-only"
demo = "wbo.ophir.dev"
code = "https://github.com/lovasoa/whitebophir"
website = "https://wbo.ophir.dev/"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "350M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/whitebophir"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/lovasoa/whitebophir/archive/refs/tags/v1.27.1.tar.gz"
    sha256 = "84d5f45d67feb9360e1e837756f46ae88e873ac3bbfe520f7af2490a777199f5"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.nodejs]
    version = "18"
